apiVersion: v1
kind: ReplicationController
metadata:
  name: demomicroprofile
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demomicroprofile
    spec:
      containers:
      - name: demomicroprofile
        image: kaiiiiii/<IMAGENAME>
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
