apiVersion: v1
kind: Service
metadata:
  name: demomicroprofileservice
  labels:
    app: demomicroprofileservice
spec:
  type: NodePort
  selector:
    app: demomicroprofile
  ports:
  - protocol: TCP
    port: 8010
    name: http
    nodePort: 30225
      
      